### PR TITLE
fix doc links

### PR DESCRIPTION
**Pull request by kirstyellis**

### CODE REVIEW

**Comment by ugocupcic** [comment]
that'll break the links on read the docs

**Comment by kirstyellis** [comment]
:/ how should it be so that they all work then?

**Comment by ugocupcic** [comment]
Not possible as far as I know :S We had that discussion with @beatrizleonand @toliver I believe. We elected to make them work on rtd not on github. @toliver still happy with that?

**Comment by toliver** [comment]
I am slightly unhappy. For the moment let's leave it like this. But when we have some time we should look  how can we have readthedocs convert them to the right format automatically. Do you think that could be done? Or are there times where this translation is not possible? (Looking at this PR it looks trivial, but...)

**Comment by ugocupcic** [comment]
Yeah looks trivial... no idea

On 2 June 2016 at 14:41, toliver notifications@github.com wrote:

> I am slightly unhappy. For the moment let's leave it like this. But when
> we have some time we should look how can we have readthedocs convert them
> to the right format automatically. Do you thing that could be done? Or are
> there times where this translation is not possible? (Looking at this PR it
> looks trivial, but...)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/shadow-robot/sr_interface/pull/166#issuecomment-223279593,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAiAfmoVRHqC6GzcLnPsNDWAAYmqx3Lkks5qHs-OgaJpZM4IsZvC
> .

## 

Ugo Cupcic_Chief Technical Architect_+44 20 7700 2487

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by beatrizleon** [comment]
Closing this pr as there is an issue filed for this: #167

**Pull request closed without merging**
