### PR TITLE
F#64 planner test suite

### LINKED ISSUE #162: create benchmarking for planners

### PR DESCRIPTION
**Pull request by kirstyellis**
fixes #162

### CODE REVIEW

**Comment by kirstyellis** [comment]
gifrecord_2016-05-12_155558

**Comment by kirstyellis** [comment]
results

**Comment by kirstyellis** [comment]
gifrecord_2016-05-12_160617

**Comment by ugocupcic** [comment]
Missing rosdep for python tabulate?

**Comment by ugocupcic** [comment]
If you want to test it, I pushed this version to docker hub. To run the benchmark, simply run:

```
docker run --rm -it shadowrobot/planner_benchmarks
```

**Comment by ugocupcic** [comment]
As discussed with @kirstyellis, we probably want to refactor that pr to make it easier to add new scenes, run all benchmarks on the scenes etc...

**Comment by ugocupcic** [comment]
Closing as we'll address this in another pr.

**Pull request closed without merging**
